module.exports = {
    shape: 'shape',
    perimeter: 'perimeter',

    SOURCE_PORT: 'sourcePort',
    TARGET_PORT: 'targetPort',
    PORT_CONSTRAINT: 'portConstraint',
    PORT_CONSTRAINT_ROTATION: 'portConstraintRotation',

    opacity: 'opacity',
    TEXT_OPACITY: 'textOpacity',
    OVERFLOW: 'overflow',
    ORTHOGONAL: 'orthogonal',
    EXIT_X: 'exitX',
    EXIT_Y: 'exitY',
    EXIT_PERIMETER: 'exitPerimeter',
    ENTRY_X: 'entryX',
    ENTRY_Y: 'entryY',
    ENTRY_PERIMETER: 'entryPerimeter',
    WHITE_SPACE: 'whiteSpace',
    rotation: 'rotation',

    SWIMLANE_FILL_COLOR: 'swimlaneFillColor',
    MARGIN: 'margin',

    fillColor: 'fillColor',
    gradientColor: 'gradientColor',
    gradientDirection: 'gradientDirection',

    strokeColor: 'strokeColor',
    strokeWidth: 'strokeWidth',


    SEPARATOR_COLOR: 'separatorColor',

    ALIGN: 'align',
    VERTICAL_ALIGN: 'verticalAlign',



    IMAGE_ASPECT: 'imageAspect',
    IMAGE_ALIGN: 'imageAlign',
    IMAGE_VERTICAL_ALIGN: 'imageVerticalAlign',

    glass: 'glass',

    IMAGE: 'image',
    IMAGE_WIDTH: 'imageWidth',
    IMAGE_HEIGHT: 'imageHeight',
    IMAGE_BACKGROUND: 'imageBackground',
    IMAGE_BORDER: 'imageBorder',

    flipH: 'flipH',
    flipV: 'flipV',

    NO_LABEL: 'noLabel',
    NO_EDGE_STYLE: 'noEdgeStyle',

    LABEL_WIDTH: 'labelWidth',
    LABEL_POSITION: 'labelPosition',
    VERTICAL_LABEL_POSITION: 'verticalLabelPosition',
    LABEL_BACKGROUND_COLOR: 'labelBackgroundColor',
    LABEL_BORDER_COLOR: 'labelBorderColor',
    LABEL_PADDING: 'labelPadding',

    INDICATOR_SHAPE: 'indicatorShape',
    INDICATOR_IMAGE: 'indicatorImage',
    INDICATOR_COLOR: 'indicatorColor',
    INDICATOR_STROKE_COLOR: 'indicatorStrokeColor',
    INDICATOR_GRADIENT_COLOR: 'indicatorGradientColor',
    INDICATOR_SPACING: 'indicatorSpacing',
    INDICATOR_WIDTH: 'indicatorWidth',
    INDICATOR_HEIGHT: 'indicatorHeight',
    INDICATOR_DIRECTION: 'indicatorDirection',

    shadow: 'shadow',
    SEGMENT: 'segment',
    startArrow: 'startArrow',
    endArrow: 'endArrow',
    endSize: 'endSize',
    startSize: 'startSize',
    SWIMLANE_LINE: 'swimlaneLine',
    END_FILL: 'endFill',
    START_FILL: 'startFill',
    dashed: 'dashed',
    DASH_PATTERN: 'dashPattern',
    rounded: 'rounded',
    CURVED: 'curved',
    ARCSIZE: 'arcSize',
    SMOOTH: 'smooth',
    SOURCE_PERIMETER_SPACING: 'sourcePerimeterSpacing',
    TARGET_PERIMETER_SPACING: 'targetPerimeterSpacing',
    PERIMETER_SPACING: 'perimeterSpacing',
    spacing: 'spacing',
    SPACING_TOP: 'spacingTop',
    SPACING_LEFT: 'spacingLeft',
    SPACING_BOTTOM: 'spacingBottom',
    SPACING_RIGHT: 'spacingRight',
    HORIZONTAL: 'horizontal',
    direction: 'direction',
    ELBOW: 'elbow',
    FONT_COLOR: 'fontColor',
    FONT_FAMILY: 'fontFamily',
    FONT_SIZE: 'fontSize',
    FONT_STYLE: 'fontStyle',
    ASPECT: 'aspect',
    AUTOSIZE: 'autosize',
    FOLDABLE: 'foldable',
    EDITABLE: 'editable',
    BENDABLE: 'bendable',
    MOVABLE: 'movable',
    RESIZABLE: 'resizable',
    ROTATABLE: 'rotatable',
    CLONEABLE: 'cloneable',
    DELETABLE: 'deletable',
    EDGE: 'edgeStyle',
    LOOP: 'loopStyle',
    ROUTING_CENTER_X: 'routingCenterX',
    ROUTING_CENTER_Y: 'routingCenterY'
};
